[package]
name = "bytes-literal"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
lifetimed-bytes = { git = "https://github.com/vorot93/lifetimed-bytes" }
hex-literal = "0.3"
